name: ci
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: alexischarp/ci-templates/.github/workflows/build-push.yml@main
    with:
      image: 'ghcr.io/alexischarp/home-portal'
      tags: |
        prod
        latest
